### PR TITLE
Reword & Reformat

### PR DESCRIPTION
**Pull request by FireController1847**
Since I just got out of my Business English class in college, I re-read the bot best practices and realized how many grammar and spelling mistakes there were. This is an attempt to fix that. I also took the time to make it easier to read and in a better format for newcomers. The meaning of each point did not change at all, it is just worded differently (and imo easier to read).

I'd love to get some people to review this before I push it, though!

### CODE REVIEW

**Review by ItzNxthaniel — APPROVED** [review]
Looks good.

**Review by Wist9063 — APPROVED** [review]
it looks pretty great and a nice look.

**Comment by burritosoftware** [comment]
Pretty good! However, line 63 should maybe be changed to "places to ask for help" instead of "how to ask for help". Overall, the changes seems really nice!

**Review by burritosoftware — CHANGES_REQUESTED** [review]
Great! Only issue is with line `63`. This line should be changed from "how to ask for help" to "places to ask for help". The why is because there are many ways to ask for help, from servers to help commands and websites.

**Review by burritosoftware — APPROVED** [review]
Nice! Looks great.

**Comment by averycblack** [comment]
Looks good

**Review by averycblack — APPROVED** [review]

**Pull request merged**
